### ISSUE TITLE
Response body of PROPFIND is URL-encoded.

### ISSUE THREAD

**Issue by SawamiWataru** [personium/personium-core#219]
When executing collection propfind, The Japanese part of the collection name is displayed as URLencode.

**How to respond**

1. Correct it so that it does not call the method that is performing the URL encoding process.
1. Since the method performing the URL encoding process includes the process of omitting the trailing "/", only that process is added.

**Comment by KourokiTakuto** [comment]
Not only EngineServiceCollection, but also ODataCollection and WebDAVCollection garbled.
However, as for ODataCollection, garbled directories and non-garbled directories are created.
00_ $ metadata.xml is created in a directory that is not garbled.

**Comment by KourokiTakuto** [comment]
When executing collection propfind, The Japanese part of the collection name is displayed as URLencode.

**How to respond**
1. Correct it so that it does not call the method that is performing the URL encoding process.

1. Since the method performing the URL encoding process includes the process of omitting the trailing "/", only that process is added.

**Comment by SawamiWataru** [comment]
Released v1.7.3.
