### ISSUE TITLE
Use secure hash in password authentication

### ISSUE THREAD

**Issue by shimono** [personium/personium-core#339]
https://github.com/shimono/personium-docs-draft/wiki/Fix-Password-Hash-Vulnerability-(ja)

**Comment by Akira-Ohishi** [comment]
It is written variously in the wiki, but at present it corresponds with the following policy.

- The new hash algorithm is called "SCrypt".
  (The "Argon2id" Java library is personally created and is not acceptable at this time.)
- It does not provide a mechanism to automatically convert password hashes for existing accounts.
  The double hashing method is not practical because of various problems.

**Comment by SawamiWataru** [comment]
Released v1.7.8
