### ISSUE TITLE
When a large number of Rules are registered in Unit, it takes time to start personium (tomcat).

### ISSUE THREAD

**Issue by SawamiWataru** [personium/personium-core#370]
Reason:
This is because all the rules are set at startup.

**Comment by Akira-Ohishi** [comment]
Please consider whether it can correspond to the following.
- Load when Rule is called.

**Comment by Akira-Ohishi** [comment]
I think division is difficult.
- It is necessary to detect timer events etc., and it is necessary to read all the rules when tomcat is started.
- Depending on the timing of delayed reading, there is a risk that the process will timeout.

**Comment by Akira-Ohishi** [comment]
I examined again.

- Search for cells with timer events.
- Load Rule at startup only for the above cells.
- Other cells read Rule at the first reference.

It seems that there is no problem if it makes it.


#### Anxious point:
In order to search for cells containing timer events, it is necessary to search across the Indexes of Rule divided into multiple schemas.
Although the realization itself is possible, please make sure that there is no problem in terms of performance.

**Comment by SawamiWataru** [comment]
Released v1.7.13
