### ISSUE TITLE
Some Unittests that use memcached fail.

### ISSUE THREAD

**Issue by SawamiWataru** [personium/personium-core#416]

**Comment by Akira-Ohishi** [comment]
If an increment request comes simultaneously from the state where the corresponding key value does not exist, one process fails and an error occurs. (A problem with MemchachedClient)

In particular, since the key value is deleted when the cell access count reaches 0, the above-mentioned current condition is likely to occur.

Therefore, exclusive control is required when incrementing and decrementing.

**Comment by Akira-Ohishi** [comment]
For cell status control, getLongValue, createLongValue and deleteLongValue are used.
Memcached's incr is unstable as described above, so do not use these unless incrementing.

**Comment by Akira-Ohishi** [comment]
Thread-unsafe methods of "io.personium.core.utils.MemcachedClient".
- incrementLongValue
- createLongValue
- decrementLongValue
- put

**Comment by SawamiWataru** [comment]
Released v1.7.12_es6.6.1
