### ISSUE TITLE
Request to {targetcell}/__message/port is performed by TYPE_INSECURE.

### ISSUE THREAD

**Issue by nisiguti** [personium/personium-core#45]
https://github.com/personium/personium-core/blob/master/src/main/java/io/personium/core/rs/cell/MessageODataResource.java#L490

**Comment by yoh1496** [comment]
Since version 1.6.0, the code is moved to

https://github.com/personium/personium-core/blob/develop/src/main/java/io/personium/core/rs/odata/ODataSentMessageResource.java#L434

from 

https://github.com/personium/personium-core/blob/1.5.0/src/main/java/io/personium/core/rs/cell/MessageODataResource.java#L490

**Comment by shimono** [comment]
If we fix this, testing using HTTPS may get difficult. 
But we still can test using HTTP, so it won't be a problem.
Let us fix this issue ASAP.
